[build]
  command = "jekyll build"
  publish = "_site"

[template.environment]
  STATUSKIT_PAGE_TITLE = "title for the page"
  STATUSKIT_COMPANY_LOGO = "url to your company's logo"
  STATUSKIT_SUPPORT_CONTACT_LINK = "url to your support page"
  STATUSKIT_RESOURCES_LINK = "url to your knowledge base page"